// Writes shared/src/abis.ts from the Foundry build output, so the site, keeper and agents share one ABI source.
// Run after `forge build`: npm run abis
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "contracts", "out");

const contracts = {
  bondlineMarketAbi: ["BondlineMarket.sol", "BondlineMarket"],
  bondlineCoverAbi: ["BondlineCover.sol", "BondlineCover"],
  agentAccountAbi: ["AgentAccount.sol", "AgentAccount"],
  oracleVenueAbi: ["OracleVenue.sol", "OracleVenue"],
  mirrorFeedAbi: ["MirrorFeed.sol", "MirrorFeed"],
  usdgAbi: ["IUSDG.sol", "IUSDG"],
  aggregatorV3Abi: ["IAggregatorV3.sol", "IAggregatorV3"],
};

let ts = "// Generated by scripts/export-abis.mjs from contracts/out. Do not edit by hand.\n\n";
for (const [name, [file, contract]] of Object.entries(contracts)) {
  const artifact = JSON.parse(readFileSync(join(out, file, `${contract}.json`), "utf8"));
  ts += `export const ${name} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n\n`;
}
writeFileSync(join(root, "shared", "src", "abis.ts"), ts);
console.log(`wrote shared/src/abis.ts (${Object.keys(contracts).length} ABIs)`);
