// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

// GENERATED by stylus/scripts/gen-consts.mjs from shared/src/pricing.ts normalCdf(). Do not edit.
// Every value is the decimal literal from the TypeScript model, as an integer at the model's 1e30 scale.
library PricerConsts {
    uint256 internal constant HART_N0 = 352624965998911 * 1e14; // 3.52624965998911e-2
    uint256 internal constant HART_N1 = 7003830644436880 * 1e14; // 0.700383064443688
    uint256 internal constant HART_N2 = 63739622035316500 * 1e14; // 6.37396220353165
    uint256 internal constant HART_N3 = 339128660783830000 * 1e14; // 33.912866078383
    uint256 internal constant HART_N4 = 1120792914978710000 * 1e14; // 112.079291497871
    uint256 internal constant HART_N5 = 2212135961699310000 * 1e14; // 221.213596169931
    uint256 internal constant HART_N6 = 2202068679123760000 * 1e14; // 220.206867912376
    uint256 internal constant HART_D0 = 883883476483184 * 1e14; // 8.83883476483184e-2
    uint256 internal constant HART_D1 = 17556671631826400 * 1e14; // 1.75566716318264
    uint256 internal constant HART_D2 = 160641775792070000 * 1e14; // 16.064177579207
    uint256 internal constant HART_D3 = 867807322029461000 * 1e14; // 86.7807322029461
    uint256 internal constant HART_D4 = 2965642487796740000 * 1e14; // 296.564248779674
    uint256 internal constant HART_D5 = 6373336333788310000 * 1e14; // 637.333633378831
    uint256 internal constant HART_D6 = 7938265125199480000 * 1e14; // 793.826512519948
    uint256 internal constant HART_D7 = 4404137358247520000 * 1e14; // 440.413735824752
    /// Hart's branch point (7.07106781186547).
    uint256 internal constant HART_CUTOFF = 70710678118654700 * 1e14;
    /// Continued-fraction start (0.65).
    uint256 internal constant CF_B0 = 6500000000000000 * 1e14;
    /// 2.506628274631
    uint256 internal constant CF_SQRT_2PI = 25066282746310000 * 1e14;
    /// N(-z) is taken as 0 above this z (37), like the TypeScript model.
    uint256 internal constant Z_MAX = 37;
}
