// Generates src/consts.rs (Stylus) and evm/src/PricerConsts.sol (EVM twin) from the decimal literals in
// shared/src/pricing.ts normalCdf(), so both integer models use the same coefficients digit for digit.
// Run: node stylus/scripts/gen-consts.mjs
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const src = readFileSync(join(here, "../../shared/src/pricing.ts"), "utf8");
const fn = src.slice(src.indexOf("export function normalCdf"), src.indexOf("export interface PricingInputs"));

// "3.52624965998911e-2" or "220.206867912376" -> integer scaled by 1e16 (all coefficients have <= 16 decimals).
function scaled16(lit) {
  const [mant, exp = "0"] = lit.split("e");
  const [ip, fp = ""] = mant.split(".");
  const e = Number(exp);
  let digits = ip + fp; // value = digits * 10^(e - fp.length)
  const shift = 16 + e - fp.length;
  if (shift < 0) throw new Error(`too many decimals: ${lit}`);
  return (BigInt(digits) * 10n ** BigInt(shift)).toString();
}

const num = (re) => [...fn.matchAll(re)].map((m) => m[1]);
// Horner lines: "let n = A * z + B;" then "n = n * z + C;" ...
const nLits = [fn.match(/let n = ([0-9.e-]+) \* z \+ ([0-9.e-]+);/).slice(1), ...[...fn.matchAll(/n = n \* z \+ ([0-9.e-]+);/g)].map((m) => [m[1]])].flat();
const dLits = [fn.match(/let d = ([0-9.e-]+) \* z \+ ([0-9.e-]+);/).slice(1), ...[...fn.matchAll(/d = d \* z \+ ([0-9.e-]+);/g)].map((m) => [m[1]])].flat();
const cutoff = fn.match(/z < ([0-9.]+)\)/)[1];
const b0 = fn.match(/let b = z \+ ([0-9.]+);/)[1];
const sqrt2pi = fn.match(/e \/ b \/ ([0-9.]+)/)[1];
const zmax = fn.match(/z > ([0-9]+)\)/)[1];
const hartN = nLits.length, hartD = dLits.length;
if (hartN !== 7 || hartD !== 8) throw new Error(`unexpected coefficient counts ${hartN} ${hartD}`);

const arr = (name, lits) =>
  `#[rustfmt::skip]\npub const ${name}: [u128; ${lits.length}] = [\n${lits.map((l) => `    ${scaled16(l)}, // ${l}`).join("\n")}\n];\n`;
const out = `// GENERATED by stylus/scripts/gen-consts.mjs from shared/src/pricing.ts normalCdf(). Do not edit.
// Every value is the decimal literal from the TypeScript model times 1e16.

pub const COEF_SCALE_EXP: u32 = 16;
${arr("HART_N", nLits)}${arr("HART_D", dLits)}/// Hart's branch point (${cutoff}).
pub const HART_CUTOFF: u128 = ${scaled16(cutoff)};
/// Continued-fraction start (${b0}).
pub const CF_B0: u128 = ${scaled16(b0)};
/// ${sqrt2pi}
pub const CF_SQRT_2PI: u128 = ${scaled16(sqrt2pi)};
/// N(-z) is taken as 0 above this z (${zmax}), like the TypeScript model.
pub const Z_MAX: u128 = ${zmax};
`;
writeFileSync(join(here, "../src/consts.rs"), out);

// Solidity: the same integers, written as literal * 1e14 (= literal * 1e16 coefficient scale -> 1e30 model scale).
const solArr = (name, lits) =>
  lits.map((l, i) => `    uint256 internal constant ${name}${i} = ${scaled16(l)} * 1e14; // ${l}`).join("\n");
const sol = `// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

// GENERATED by stylus/scripts/gen-consts.mjs from shared/src/pricing.ts normalCdf(). Do not edit.
// Every value is the decimal literal from the TypeScript model, as an integer at the model's 1e30 scale.
library PricerConsts {
${solArr("HART_N", nLits)}
${solArr("HART_D", dLits)}
    /// Hart's branch point (${cutoff}).
    uint256 internal constant HART_CUTOFF = ${scaled16(cutoff)} * 1e14;
    /// Continued-fraction start (${b0}).
    uint256 internal constant CF_B0 = ${scaled16(b0)} * 1e14;
    /// ${sqrt2pi}
    uint256 internal constant CF_SQRT_2PI = ${scaled16(sqrt2pi)} * 1e14;
    /// N(-z) is taken as 0 above this z (${zmax}), like the TypeScript model.
    uint256 internal constant Z_MAX = ${zmax};
}
`;
mkdirSync(join(here, "../evm/src"), { recursive: true });
writeFileSync(join(here, "../evm/src/PricerConsts.sol"), sol);
console.log(out);
