/**
 * Writes stylus/vectors.json: the TypeScript model's answers, rounded to the contract's integer units, for
 * shared/src/pricing.ts PRICING_VECTORS plus a wider grid. The Rust tests (cargo test) must reproduce every integer.
 *
 * Units: every output is basis points scaled by 1e4 (fraction * 1e8; 1 = 0.0001 bps).
 * Rounding: Math.round of the unrounded model value (half up, values are >= 0), once per output, from the
 * double-precision model. `fair` is the rounding of the unrounded fair, not the sum of the rounded parts.
 *
 * Run (from /Users/naitik/surety): npx tsx stylus/scripts/vectors.ts
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { PRICING_VECTORS, priceCover } from "../../shared/src/pricing.ts";

const UNIT = 1e4; // bps -> units

export interface Row {
  name?: string;
  wBps: number;
  sigmaBps: number;
  termDays: number;
  limitBps: number;
  capBps: number;
  pHitBps: number;
  gapBps: number;
  riskBps: number;
  reserveBps: number;
  fairBps: number;
}

/** The TypeScript model, rounded to the contract's units. */
export function modelRow(wBps: number, sigmaBps: number, termDays: number, limitBps: number, capBps: number, name?: string): Row {
  const b = priceCover({
    stockShare: wBps / 10_000,
    sigma: sigmaBps / 10_000,
    limit: limitBps / 10_000,
    cap: capBps / 10_000,
    termDays,
  }).bps;
  const r = (x: number) => Math.round(x * UNIT);
  return {
    ...(name ? { name } : {}),
    wBps,
    sigmaBps,
    termDays,
    limitBps,
    capBps,
    pHitBps: r(b.pTouch),
    gapBps: r(b.gap),
    riskBps: r(b.riskPart),
    reserveBps: r(b.reservePart),
    fairBps: r(b.fair),
  };
}

const rows: Row[] = [];

// 1. The ten fixed vectors in shared/src/pricing.ts. Also check them against their Python (math.erfc) values.
let pythonMismatch = 0;
for (const v of PRICING_VECTORS) {
  const row = modelRow(v.stockShareBps, v.sigmaBps, v.termDays, v.limitBps, v.capBps, v.name);
  const py = [v.pTouchBps, v.gapBps, v.riskBps, v.reserveBps, v.fairBps].map((x) => Math.round(x * UNIT));
  const ts = [row.pHitBps, row.gapBps, row.riskBps, row.reserveBps, row.fairBps];
  if (py.some((x, i) => x !== ts[i])) {
    pythonMismatch++;
    console.warn(`python-vs-ts rounding differs for "${v.name}": python ${py} ts ${ts}`);
  }
  rows.push(row);
}

// 2. A grid.
const W = [0, 1, 100, 500, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000];
const SIGMA = [0, 500, 1000, 2500, 3932, 5000, 5457, 7500, 10000, 15000, 30000];
const TERM = [1, 7, 14, 30, 60, 90, 180, 365];
const LIMIT = [10, 50, 100, 250, 500, 1000, 1500, 2000, 2500, 2900, 2999];
const CAP = [3000, 5000, 10000];
for (const c of CAP)
  for (const l of LIMIT) {
    if (l >= c) continue;
    for (const w of W)
      for (const s of SIGMA)
        for (const t of TERM) {
          // Keep the file small: the full cross product is ~46k rows. Take a deterministic third.
          if (((w + 3 * s + 7 * t + 11 * l + c) >>> 0) % 3 !== 0) continue;
          rows.push(modelRow(w, s, t, l, c));
        }
  }

// 3. Seeded pseudo-random rows over the whole domain (mulberry32).
let seed = 0x0b0d11e5;
const rnd = () => {
  seed = (seed + 0x6d2b79f5) >>> 0;
  let t = seed;
  t = Math.imul(t ^ (t >>> 15), t | 1);
  t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
};
const int = (lo: number, hi: number) => lo + Math.floor(rnd() * (hi - lo + 1));
for (let i = 0; i < 2500; i++) {
  const cap = rnd() < 0.7 ? 3000 : int(2, 10000);
  rows.push(modelRow(int(0, 10000), int(0, 40000), int(1, 730), int(1, cap - 1), cap));
}

// 4. Edges: limit one below cap, one bps, extreme sigma (far tail, d > 37 and the continued-fraction branch).
for (const [w, s, t, l, c] of [
  [10000, 1, 1, 2999, 3000], [1, 1, 1, 1, 3000], [10000, 1_000_000, 36500, 2999, 3000], [1, 100, 30, 2999, 3000],
  [1, 1, 365, 2999, 3000], [50, 500, 1, 2999, 3000], [100, 1000, 7, 2000, 3000], [200, 1000, 7, 2000, 3000], [150, 2000, 30, 1500, 3000],
  [10000, 1_000_000, 1, 1, 2], [10000, 1_000_000, 36500, 1, 10000], [0, 0, 30, 1000, 3000], [5000, 0, 30, 1000, 3000], [0, 5000, 30, 1000, 3000],
] as const) rows.push(modelRow(w, s, t, l, c));

// Drop exact duplicates.
const seen = new Set<string>();
const unique = rows.filter((r) => {
  const k = `${r.wBps},${r.sigmaBps},${r.termDays},${r.limitBps},${r.capBps}`;
  if (seen.has(k)) return false;
  seen.add(k);
  return true;
});

const out = {
  note:
    "Generated by stylus/scripts/vectors.ts from shared/src/pricing.ts (double precision), rounded half up to integer units. " +
    "Every output is basis points scaled by 1e4 (1 = 0.0001 bps). fair is the rounding of the unrounded fair. Do not edit.",
  count: unique.length,
  fixed: PRICING_VECTORS.length,
  vectors: unique,
};
const here = dirname(fileURLToPath(import.meta.url));
writeFileSync(join(here, "../vectors.json"), JSON.stringify(out) + "\n");

// The same rows, flattened for the Solidity test (evm/test/PricerVectors.t.sol), which parses one array of integers:
// per row w, sigma, term, limit, cap, pHit, gap, risk, reserve, fair.
const flat = unique.flatMap((r) => [r.wBps, r.sigmaBps, r.termDays, r.limitBps, r.capBps, r.pHitBps, r.gapBps, r.riskBps, r.reserveBps, r.fairBps]);
mkdirSync(join(here, "../evm/test"), { recursive: true });
writeFileSync(join(here, "../evm/test/vectors.flat.json"), JSON.stringify({ count: unique.length, flat }) + "\n");
console.log(`wrote ${unique.length} vectors (${PRICING_VECTORS.length} fixed); python-vs-ts rounding differences in the fixed vectors: ${pythonMismatch}`);
